# Generated by Django 5.0.3 on 2024-03-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay',
            name='name',
            field=models.CharField(default='ali', max_length=100),
            preserve_default=False,
        ),
    ]
